#!/usr/bin/env python3
"""
End-to-end tests for Neo23x0/auditd integration in SEC-AUDITD.
Tests that the neo23x0 audit rules file is well-formed and that the
alert engine correctly processes events generated by neo23x0 rule keys.
"""

import os
import re
import sys
import json
import time
import subprocess
import tempfile
import unittest
from pathlib import Path

# Project root and key directories
PROJECT_ROOT = Path(__file__).parent.parent.absolute()
ALERT_ENGINE_DIR = PROJECT_ROOT / 'alert-engine'
AUDIT_RULES_DIR = PROJECT_ROOT / 'audit.rules.d'
NEO23X0_RULES_FILE = AUDIT_RULES_DIR / '40-neo23x0.rules'
NEO23X0_ALERT_RULES = ALERT_ENGINE_DIR / 'rules.d' / 'neo23x0.yaml'


class TestNeo23x0RulesFile(unittest.TestCase):
    """验证 40-neo23x0.rules 文件的结构和完整性"""

    def test_rules_file_exists(self):
        """规则文件应存在"""
        self.assertTrue(
            NEO23X0_RULES_FILE.exists(),
            f"Neo23x0 规则文件不存在: {NEO23X0_RULES_FILE}"
        )

    def test_rules_file_not_empty(self):
        """规则文件不应为空"""
        content = NEO23X0_RULES_FILE.read_text()
        self.assertGreater(len(content.strip()), 0, "规则文件不应为空")

    def test_rules_file_has_attribution_header(self):
        """规则文件应包含来源说明注释"""
        content = NEO23X0_RULES_FILE.read_text()
        self.assertIn('Neo23x0', content, "规则文件应包含 Neo23x0 来源说明")
        self.assertIn('https://github.com/Neo23x0/auditd', content,
                      "规则文件应包含项目 URL")

    def test_rules_file_no_reset_flag(self):
        """-D（清除规则）不应出现在此文件，避免与 00-base.rules 冲突"""
        lines = NEO23X0_RULES_FILE.read_text().splitlines()
        active_lines = [l.strip() for l in lines
                        if l.strip() and not l.strip().startswith('#')]
        self.assertNotIn('-D', active_lines,
                         "-D 不应出现在 40-neo23x0.rules 中（已在 00-base.rules 配置）")

    def test_rules_file_no_buffer_config(self):
        """-b（缓冲区大小）不应出现在此文件，避免与 00-base.rules 冲突"""
        lines = NEO23X0_RULES_FILE.read_text().splitlines()
        active_lines = [l.strip() for l in lines
                        if l.strip() and not l.strip().startswith('#')]
        buffer_lines = [l for l in active_lines if l.startswith('-b ')]
        self.assertEqual(len(buffer_lines), 0,
                         "-b 不应出现在 40-neo23x0.rules 中（已在 00-base.rules 配置）")

    def test_rules_file_has_ignore_flag(self):
        """-i（忽略错误）应存在，确保可选路径不阻断加载"""
        content = NEO23X0_RULES_FILE.read_text()
        self.assertIn('-i', content, "-i 标志应存在（允许可选路径）")

    def test_rules_file_contains_key_neo23x0_rules(self):
        """规则文件应包含 neo23x0 的核心规则键"""
        content = NEO23X0_RULES_FILE.read_text()
        essential_keys = [
            'process_creation', 'perm_mod', 'unauthedfileaccess',
            'tracing', 'anon_file_create', 'bpf', 'namespaces',
            'modules', 'network_modifications',
        ]
        for key in essential_keys:
            self.assertIn(key, content,
                          f"规则文件应包含规则键: {key}")

    def test_rules_file_syntax_valid_lines(self):
        """规则文件中的规则行应具有合法的 auditd 语法"""
        lines = NEO23X0_RULES_FILE.read_text().splitlines()
        valid_prefixes = ('-a ', '-w ', '-A ', '-d ', '-D', '-b ', '-f ',
                          '-e ', '-i', '-r ', '-l ')
        for line in lines:
            stripped = line.strip()
            if not stripped or stripped.startswith('#'):
                continue
            self.assertTrue(
                any(stripped.startswith(p) for p in valid_prefixes),
                f"规则行格式不合法: {stripped!r}"
            )

    def test_rules_file_sorted_after_existing(self):
        """40-neo23x0.rules 应在文件系统排序中位于 30-file.rules 之后"""
        rules_files = sorted(AUDIT_RULES_DIR.glob('*.rules'))
        names = [f.name for f in rules_files]
        self.assertIn('40-neo23x0.rules', names)
        idx = names.index('40-neo23x0.rules')
        self.assertGreater(idx, names.index('30-file.rules'),
                           "40-neo23x0.rules 应排在 30-file.rules 之后")
        self.assertLess(idx, names.index('99-finalize.rules'),
                        "40-neo23x0.rules 应排在 99-finalize.rules 之前")

    def test_all_rules_files_present(self):
        """所有预期的规则文件都应存在"""
        expected_files = [
            '00-base.rules', '10-process.rules', '20-network.rules',
            '30-file.rules', '40-neo23x0.rules', '99-finalize.rules',
        ]
        for fname in expected_files:
            self.assertTrue(
                (AUDIT_RULES_DIR / fname).exists(),
                f"规则文件应存在: {fname}"
            )


class TestNeo23x0AlertRules(unittest.TestCase):
    """验证 neo23x0.yaml 告警规则文件"""

    def test_alert_rules_file_exists(self):
        """告警规则文件应存在"""
        self.assertTrue(
            NEO23X0_ALERT_RULES.exists(),
            f"Neo23x0 告警规则文件不存在: {NEO23X0_ALERT_RULES}"
        )

    def test_alert_rules_yaml_valid(self):
        """告警规则文件应是合法的 YAML"""
        try:
            import yaml
            content = NEO23X0_ALERT_RULES.read_text()
            data = yaml.safe_load(content)
            self.assertIsNotNone(data, "YAML 内容不应为 None")
            self.assertIn('rules', data, "应包含 'rules' 键")
        except ImportError:
            self.skipTest("PyYAML 未安装，跳过 YAML 解析测试")

    def test_alert_rules_cover_key_neo23x0_keys(self):
        """告警规则应覆盖 neo23x0 的关键审计键"""
        content = NEO23X0_ALERT_RULES.read_text()
        essential_alert_keys = [
            'process_creation', 'perm_mod', 'unauthedfileaccess',
            'tracing', 'anon_file_create', 'bpf', 'namespaces',
            'modules', 'network_modifications', 'power_abuse',
            'T1070_006_timestomp',
        ]
        for key in essential_alert_keys:
            self.assertIn(key, content,
                          f"告警规则应包含审计键: {key}")

    def test_alert_rules_have_required_fields(self):
        """每条告警规则应包含必需字段"""
        try:
            import yaml
            content = NEO23X0_ALERT_RULES.read_text()
            data = yaml.safe_load(content)
            for rule in data.get('rules', []):
                self.assertIn('id', rule, f"规则缺少 id 字段: {rule}")
                self.assertIn('name', rule, f"规则缺少 name 字段: {rule}")
                self.assertIn('enabled', rule,
                              f"规则缺少 enabled 字段: {rule.get('id')}")
                self.assertIn('severity', rule,
                              f"规则缺少 severity 字段: {rule.get('id')}")
                self.assertIn('match', rule,
                              f"规则缺少 match 字段: {rule.get('id')}")
                self.assertIn('alert', rule,
                              f"规则缺少 alert 字段: {rule.get('id')}")
        except ImportError:
            self.skipTest("PyYAML 未安装，跳过 YAML 解析测试")

    def test_alert_rules_ids_unique(self):
        """告警规则 ID 应唯一"""
        try:
            import yaml
            content = NEO23X0_ALERT_RULES.read_text()
            data = yaml.safe_load(content)
            ids = [r.get('id') for r in data.get('rules', [])]
            self.assertEqual(len(ids), len(set(ids)),
                             "告警规则 ID 存在重复")
        except ImportError:
            self.skipTest("PyYAML 未安装，跳过 YAML 解析测试")

    def test_alert_rules_severity_values_valid(self):
        """告警规则的 severity 应是合法值"""
        try:
            import yaml
            valid_severities = {'low', 'medium', 'high', 'critical'}
            content = NEO23X0_ALERT_RULES.read_text()
            data = yaml.safe_load(content)
            for rule in data.get('rules', []):
                sev = rule.get('severity', '')
                self.assertIn(
                    sev, valid_severities,
                    f"规则 {rule.get('id')} 的 severity 值 '{sev}' 不合法"
                )
        except ImportError:
            self.skipTest("PyYAML 未安装，跳过 YAML 解析测试")


class TestNeo23x0EngineIntegration(unittest.TestCase):
    """端到端测试：告警引擎处理 neo23x0 规则键生成的事件"""

    def setUp(self):
        """设置测试环境"""
        self.temp_dir = tempfile.mkdtemp()
        self.audit_log = os.path.join(self.temp_dir, 'audit.log')
        self.alert_log = os.path.join(self.temp_dir, 'alert.log')
        self.config_file = os.path.join(self.temp_dir, 'config.yaml')
        self.rules_dir = os.path.join(self.temp_dir, 'rules.d')
        os.makedirs(self.rules_dir)

        config_content = f"""
engine:
  input:
    type: file
    file: {self.audit_log}
  output:
    - type: file
      path: {self.alert_log}
      format: json
  rules:
    dir: {self.rules_dir}
    reload_interval: 60
"""
        with open(self.config_file, 'w') as f:
            f.write(config_content)

        with open(self.audit_log, 'w') as f:
            pass

    def _write_neo23x0_alert_rules(self, key, rule_id=None, severity='high'):
        """写入针对特定 neo23x0 键的告警规则"""
        if rule_id is None:
            rule_id = f"neo23x0_test_{key.lower().replace('-', '_')}"
        rule_content = f"""
rules:
  - id: {rule_id}
    name: "测试 neo23x0 键: {key}"
    enabled: true
    severity: {severity}
    match:
      key: "{key}"
    alert:
      message: "Neo23x0 事件检测: {{exe}} (UID: {{uid}})"
      throttle: 0
"""
        rule_file = os.path.join(self.rules_dir, f'{rule_id}.yaml')
        with open(rule_file, 'w') as f:
            f.write(rule_content)
        return rule_id

    def _append_audit_log(self, line):
        with open(self.audit_log, 'a') as f:
            f.write(line + '\n')
            f.flush()

    def _wait_for_alerts(self, timeout=8):
        start = time.time()
        while time.time() - start < timeout:
            if os.path.exists(self.alert_log):
                with open(self.alert_log, 'r') as f:
                    content = f.read()
                    if content.strip():
                        return content
            time.sleep(0.2)
        return ""

    def _read_alerts(self):
        if not os.path.exists(self.alert_log):
            return []
        alerts = []
        with open(self.alert_log, 'r') as f:
            for line in f:
                line = line.strip()
                if line:
                    try:
                        alerts.append(json.loads(line))
                    except json.JSONDecodeError:
                        pass
        return alerts

    def tearDown(self):
        import shutil
        try:
            shutil.rmtree(self.temp_dir)
        except Exception:
            pass

    def _run_engine_test(self, rule_key, audit_event_line, expected_rule_id):
        """通用引擎测试辅助方法"""
        engine_script = ALERT_ENGINE_DIR / 'engine.py'
        self._write_neo23x0_alert_rules(rule_key, rule_id=expected_rule_id)

        proc = subprocess.Popen(
            ['python3', str(engine_script), self.config_file],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )
        try:
            time.sleep(2)
            self._append_audit_log(audit_event_line)
            time.sleep(1)
            self._wait_for_alerts(timeout=6)
            alerts = self._read_alerts()
            self.assertGreater(len(alerts), 0,
                               f"规则键 '{rule_key}' 应触发告警")
            rule_ids = [a.get('rule_id') for a in alerts]
            self.assertIn(expected_rule_id, rule_ids,
                          f"告警的 rule_id 应为 '{expected_rule_id}'")
            return alerts
        finally:
            proc.terminate()
            try:
                proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                proc.kill()

    def test_perm_mod_alert(self):
        """perm_mod 键应触发权限修改告警"""
        event = (
            'type=SYSCALL msg=audit(1234567890.123:100): '
            'arch=c000003e syscall=268 success=yes exit=0 '
            'a0=3 a1=7f1234 a2=1ed a3=0 '
            'pid=1234 uid=1000 auid=1000 '
            'comm="chmod" exe="/bin/chmod" '
            'key="perm_mod"'
        )
        self._run_engine_test('perm_mod', event, 'neo23x0_perm_mod_test')

    def test_unauthedfileaccess_alert(self):
        """unauthedfileaccess 键应触发未授权文件访问告警"""
        event = (
            'type=SYSCALL msg=audit(1234567890.456:200): '
            'arch=c000003e syscall=2 success=no exit=-13 '
            'pid=5678 uid=1001 auid=1001 '
            'comm="bash" exe="/bin/bash" '
            'key="unauthedfileaccess"'
        )
        self._run_engine_test(
            'unauthedfileaccess', event, 'neo23x0_unauthedfileaccess_test'
        )

    def test_tracing_alert(self):
        """tracing 键应触发 ptrace 告警"""
        event = (
            'type=SYSCALL msg=audit(1234567890.789:300): '
            'arch=c000003e syscall=101 success=yes exit=0 '
            'pid=9999 uid=0 auid=0 '
            'comm="gdb" exe="/usr/bin/gdb" '
            'key="tracing"'
        )
        self._run_engine_test('tracing', event, 'neo23x0_tracing_test')

    def test_anon_file_create_alert(self):
        """anon_file_create 键应触发匿名文件创建告警"""
        event = (
            'type=SYSCALL msg=audit(1234567890.100:400): '
            'arch=c000003e syscall=319 success=yes exit=3 '
            'pid=2222 uid=1000 auid=1000 '
            'comm="suspicious" exe="/tmp/suspicious" '
            'key="anon_file_create"'
        )
        self._run_engine_test(
            'anon_file_create', event, 'neo23x0_anon_file_create_test'
        )

    def test_bpf_alert(self):
        """bpf 键应触发 eBPF 程序加载告警"""
        event = (
            'type=SYSCALL msg=audit(1234567890.200:500): '
            'arch=c000003e syscall=321 success=yes exit=0 '
            'pid=3333 uid=0 auid=0 '
            'comm="unknown" exe="/tmp/ebpf_loader" '
            'key="bpf"'
        )
        self._run_engine_test('bpf', event, 'neo23x0_bpf_test')

    def test_namespaces_alert(self):
        """namespaces 键应触发命名空间操作告警"""
        event = (
            'type=SYSCALL msg=audit(1234567890.300:600): '
            'arch=c000003e syscall=272 success=yes exit=0 '
            'pid=4444 uid=1000 auid=1000 '
            'comm="unshare" exe="/usr/bin/unshare" '
            'key="namespaces"'
        )
        self._run_engine_test('namespaces', event, 'neo23x0_namespaces_test')

    def test_process_vm_alert(self):
        """process_vm 键应触发跨进程内存访问告警"""
        event = (
            'type=SYSCALL msg=audit(1234567890.400:700): '
            'arch=c000003e syscall=310 success=yes exit=100 '
            'pid=5555 uid=1000 auid=1000 '
            'comm="injector" exe="/tmp/injector" '
            'key="process_vm"'
        )
        self._run_engine_test('process_vm', event, 'neo23x0_process_vm_test')

    def test_modules_alert(self):
        """modules 键应触发内核模块操作告警"""
        event = (
            'type=SYSCALL msg=audit(1234567890.500:800): '
            'arch=c000003e syscall=175 success=yes exit=0 '
            'pid=6666 uid=0 auid=0 '
            'comm="insmod" exe="/sbin/insmod" '
            'key="modules"'
        )
        self._run_engine_test('modules', event, 'neo23x0_modules_test')

    def test_network_modifications_alert(self):
        """network_modifications 键应触发网络环境修改告警"""
        event = (
            'type=SYSCALL msg=audit(1234567890.600:900): '
            'arch=c000003e syscall=170 success=yes exit=0 '
            'pid=7777 uid=0 auid=1000 '
            'comm="hostname" exe="/bin/hostname" '
            'key="network_modifications"'
        )
        self._run_engine_test(
            'network_modifications', event,
            'neo23x0_network_modifications_test'
        )

    def test_power_abuse_alert(self):
        """power_abuse 键应触发权限滥用告警"""
        event = (
            'type=SYSCALL msg=audit(1234567890.700:1000): '
            'arch=c000003e syscall=2 success=yes exit=5 '
            'pid=8888 uid=0 auid=1001 '
            'comm="cat" exe="/bin/cat" '
            'key="power_abuse"'
        )
        self._run_engine_test('power_abuse', event, 'neo23x0_power_abuse_test')

    def test_process_creation_alert(self):
        """process_creation 键应触发进程创建告警"""
        event = (
            'type=EXECVE msg=audit(1234567890.800:1100): '
            'argc=1 a0="/bin/ls" exe="/bin/ls" '
            'key="process_creation"'
        )
        self._run_engine_test(
            'process_creation', event, 'neo23x0_process_creation_test'
        )

    def test_delete_alert(self):
        """delete 键应触发文件删除事件告警"""
        event = (
            'type=SYSCALL msg=audit(1234567890.900:1200): '
            'arch=c000003e syscall=87 success=yes exit=0 '
            'pid=1111 uid=1000 auid=1000 '
            'comm="rm" exe="/bin/rm" '
            'key="delete"'
        )
        self._run_engine_test('delete', event, 'neo23x0_delete_test')


class TestNeo23x0RulesIntegration(unittest.TestCase):
    """集成测试：验证 neo23x0 规则文件在完整规则集中的加载顺序"""

    def test_rules_directory_has_six_files(self):
        """规则目录应包含 6 个规则文件"""
        rules_files = list(AUDIT_RULES_DIR.glob('*.rules'))
        self.assertEqual(
            len(rules_files), 6,
            f"规则目录应有 6 个文件，实际有 {len(rules_files)}: "
            f"{sorted(f.name for f in rules_files)}"
        )

    def test_combined_rules_file_generation(self):
        """合并所有规则文件应产生完整的规则集"""
        import tempfile
        combined_content = ""
        for rules_file in sorted(AUDIT_RULES_DIR.glob('*.rules')):
            combined_content += rules_file.read_text() + "\n"

        # 验证合并后包含基础配置
        self.assertIn('-b 8192', combined_content, "合并规则应包含缓冲区配置")
        self.assertIn('-f 1', combined_content, "合并规则应包含失败模式配置")

        # 验证包含 neo23x0 的关键规则
        self.assertIn('process_creation', combined_content)
        self.assertIn('perm_mod', combined_content)
        self.assertIn('unauthedfileaccess', combined_content)
        self.assertIn('anon_file_create', combined_content)

    def test_neo23x0_keys_not_duplicate_base_keys(self):
        """neo23x0 引入的核心新键不应与已有规则键重复（保持清晰的职责边界）"""
        neo23x0_content = NEO23X0_RULES_FILE.read_text()
        existing_files = [
            '00-base.rules', '10-process.rules',
            '20-network.rules', '30-file.rules',
        ]
        existing_content = ""
        for fname in existing_files:
            existing_content += (AUDIT_RULES_DIR / fname).read_text()

        # neo23x0 特有的键不应出现在原有规则中
        neo23x0_unique_keys = [
            'perm_mod', 'unauthedfileaccess', 'tracing', 'anon_file_create',
            'T1070_006_timestomp', 'bpf', 'namespaces', 'process_vm',
            'power_abuse', '32bit_abi', 'process_creation',
        ]
        for key in neo23x0_unique_keys:
            self.assertNotIn(
                f'key="{key}"', existing_content,
                f"键 '{key}' 是 neo23x0 特有键，不应出现在原有规则文件中"
            )
            self.assertIn(
                key, neo23x0_content,
                f"键 '{key}' 应出现在 40-neo23x0.rules 中"
            )

    def test_alert_engine_loads_neo23x0_rules(self):
        """告警引擎应能加载 neo23x0 告警规则"""
        sys.path.insert(0, str(ALERT_ENGINE_DIR))
        try:
            from engine import RuleEngine
            import tempfile

            temp_dir = tempfile.mkdtemp()
            try:
                config_file = os.path.join(temp_dir, 'config.yaml')
                rules_dir = os.path.join(temp_dir, 'rules.d')
                os.makedirs(rules_dir)

                # 复制 neo23x0 告警规则到测试目录
                import shutil
                shutil.copy(str(NEO23X0_ALERT_RULES),
                            os.path.join(rules_dir, 'neo23x0.yaml'))

                config_content = f"""
engine:
  input:
    type: file
    file: /tmp/test_audit.log
  output:
    - type: file
      path: /tmp/test_alert.log
      format: json
  rules:
    dir: {rules_dir}
    reload_interval: 60
"""
                with open(config_file, 'w') as f:
                    f.write(config_content)

                engine = RuleEngine(config_file)
                self.assertGreater(len(engine.rules), 0,
                                   "引擎应加载 neo23x0 告警规则")

                # 验证关键规则 ID 已加载
                rule_ids = {r['id'] for r in engine.rules}
                expected_ids = [
                    'neo23x0_process_creation',
                    'neo23x0_perm_mod',
                    'neo23x0_unauthedfileaccess',
                    'neo23x0_tracing',
                    'neo23x0_anon_file_create',
                    'neo23x0_bpf',
                    'neo23x0_namespaces',
                    'neo23x0_modules',
                    'neo23x0_power_abuse',
                ]
                for rule_id in expected_ids:
                    self.assertIn(rule_id, rule_ids,
                                  f"引擎应包含规则: {rule_id}")
            finally:
                import shutil
                shutil.rmtree(temp_dir)
        finally:
            if str(ALERT_ENGINE_DIR) in sys.path:
                sys.path.remove(str(ALERT_ENGINE_DIR))

    def test_neo23x0_rule_matching(self):
        """告警引擎应能匹配 neo23x0 规则键的事件"""
        sys.path.insert(0, str(ALERT_ENGINE_DIR))
        try:
            from engine import RuleEngine
            import tempfile
            import shutil

            temp_dir = tempfile.mkdtemp()
            try:
                config_file = os.path.join(temp_dir, 'config.yaml')
                rules_dir = os.path.join(temp_dir, 'rules.d')
                os.makedirs(rules_dir)

                shutil.copy(str(NEO23X0_ALERT_RULES),
                            os.path.join(rules_dir, 'neo23x0.yaml'))

                config_content = f"""
engine:
  input:
    type: file
    file: /tmp/test_audit.log
  output:
    - type: file
      path: /tmp/test_alert.log
      format: json
  rules:
    dir: {rules_dir}
    reload_interval: 60
"""
                with open(config_file, 'w') as f:
                    f.write(config_content)

                engine = RuleEngine(config_file)

                # 查找 perm_mod 规则
                perm_mod_rule = None
                for rule in engine.rules:
                    if rule['id'] == 'neo23x0_perm_mod':
                        perm_mod_rule = rule
                        break

                self.assertIsNotNone(perm_mod_rule, "应找到 perm_mod 规则")

                # 测试匹配
                event_match = {'key': 'perm_mod', 'exe': '/bin/chmod',
                               'uid': 1000}
                self.assertTrue(engine._match_rule(event_match, perm_mod_rule),
                                "perm_mod 事件应被匹配")

                event_no_match = {'key': 'process_exec', 'exe': '/bin/ls',
                                  'uid': 1000}
                self.assertFalse(
                    engine._match_rule(event_no_match, perm_mod_rule),
                    "process_exec 事件不应匹配 perm_mod 规则"
                )

                tracing_rule = None
                for rule in engine.rules:
                    if rule['id'] == 'neo23x0_tracing':
                        tracing_rule = rule
                        break

                self.assertIsNotNone(tracing_rule, "应找到 tracing 规则")
                legit_gdb = {'key': 'tracing', 'process': 'gdb',
                             'exe': '/usr/bin/gdb'}
                renamed_strace = {'key': 'tracing', 'process': 'strace',
                                  'exe': '/tmp/strace'}

                self.assertTrue(engine._in_whitelist(legit_gdb, tracing_rule))
                self.assertFalse(
                    engine._in_whitelist(renamed_strace, tracing_rule),
                    "重命名为 strace 的非系统路径程序不应进入 ptrace 白名单"
                )
            finally:
                shutil.rmtree(temp_dir)
        finally:
            if str(ALERT_ENGINE_DIR) in sys.path:
                sys.path.remove(str(ALERT_ENGINE_DIR))


def run_tests():
    """运行所有 neo23x0 集成测试"""
    loader = unittest.TestLoader()
    suite = unittest.TestSuite()

    suite.addTests(loader.loadTestsFromTestCase(TestNeo23x0RulesFile))
    suite.addTests(loader.loadTestsFromTestCase(TestNeo23x0AlertRules))
    suite.addTests(loader.loadTestsFromTestCase(TestNeo23x0RulesIntegration))
    suite.addTests(loader.loadTestsFromTestCase(TestNeo23x0EngineIntegration))

    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)
    return result.wasSuccessful()


if __name__ == '__main__':
    success = run_tests()
    sys.exit(0 if success else 1)
